apiVersion: v1
kind: Service
metadata:
  name: nodejsapp
spec:
  selector:
    app: nodejsapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30050  # Adjust as needed
  type: NodePort
